openapi: 3.0.0   # Open api version

info:
  title: GPT2-Futurama
  version: "v0.1"
  contact:
    name: AInizer - Lee hoseop
  description: |
    This app is generate Futurama script as array.
    ---
      How to use:
      * First, Choose Futurama character name.
      * Second, Fill what the character will say in text. This will be base of script.
      * And then, Fill number in length. Text is created as long as "length". I recommend between 100 and 300.
      * If length is so big, generate time will be long.
    ---
    And you can use this in [demo page](https://master-gpt2-futurama-fpem123.endpoint.ainize.ai/).

    Fine tuning data reference >> [Futurama Transcripts](https://www.kaggle.com/josephvm/futurama-seasons-16-transcripts?select=only_spoken_text.csv)

servers:
  - url: https://master-gpt2-futurama-fpem123.endpoint.ainize.ai/

paths:
  /futurama:
    post:
      requestBody:
        required: true
        description: |
          This request will generate Futurama script.

          Request body example

              name: Fry
              text: Hello,
              length: 150

        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  enum: [Fry, Leela, Bender, Farnsworth, Zoidberg, Wong, Conrad, Scruffington]
                  description: "Futurama character name."
                text:
                  type: string
                  description: "The base of script."
                length:
                  type: string
                  description: "The size of text."
              required:
                - name
                - text
                - length
      responses:   # Set response
        '200':
          description: "Successful Response"
          content:
            application/json:
              schema:
                type: object
        '400':
          description: "Bad Request Error"
        '429':
          description: "Too many requests"
        '500':
          description: "Server-side Error"